# export-claude-env.ps1 - regenerate claude-env/ (the Shield's portable Claude
# steering) from this PC's ~/.claude. One-way: DEVIL ~/.claude -> repo claude-env/
# -> (git push) -> Shield pulls -> docker-bringup/claude-steer.sh applies it.
#
# Syncs: CLAUDE.md (offload + Windows-shell rules stripped), skills/, agents/
# (symlinks dereferenced to real content). Deliberately NOT synced: settings.json
# (hand-authored Shield variant - no ollama/Windows hooks, no MCP) and .claude.json
# (host-bound: OAuth token + G:\ paths - never leaves the PC).
#
# Re-run after changing global skills/agents/CLAUDE.md, then commit + push.
$ErrorActionPreference = 'Stop'

$src  = Join-Path $env:USERPROFILE '.claude'
$repo = Split-Path -Parent $PSScriptRoot
$dst  = Join-Path $repo 'claude-env'

# deref-copy an ALLOWLISTED subset of a ~/.claude subdir, resolving symlinked
# entries to real content. Allowlist (not copy-everything) because the repo is
# PUBLIC: plugin skills like `council` carry personal workstation paths, so only
# the user-authored, public-safe steering is synced.
function Sync-Dir([string]$name, [string[]]$allow) {
  $from = Join-Path $src $name
  $to   = Join-Path $dst $name
  if (Test-Path $to) { Remove-Item $to -Recurse -Force }
  New-Item -ItemType Directory -Path $to -Force | Out-Null
  if (-not (Test-Path $from)) { Write-Warning "no $from - skipping"; return }
  foreach ($want in $allow) {
    $e = Get-Item (Join-Path $from $want) -ErrorAction SilentlyContinue
    if (-not $e) { Write-Warning "  allowlisted but missing: $name/$want"; continue }
    if ($e.LinkType) { $real = Get-Item $e.Target } else { $real = $e }
    Copy-Item $real.FullName (Join-Path $to $e.Name) -Recurse -Force
  }
  $n = (Get-ChildItem $to).Count
  Write-Host "synced $name/ ($n of $($allow.Count) allowlisted)"
}

# Hard gate: a PUBLIC repo must never receive a workstation path or username path.
function Assert-NoPII {
  $hits = Get-ChildItem $dst -Recurse -File |
    Select-String -Pattern 'C:\\Users\\|[A-Z]:\\\\?Documents|ed-afk|starbot' -List
  if ($hits) {
    $hits | ForEach-Object { Write-Host "PII: $($_.Path):$($_.LineNumber)" }
    throw "PII detected in claude-env/ - refusing. Fix the allowlist/transform."
  }
  Write-Host "PII guard: clean"
}

# CLAUDE.md: drop the two offload-only sections (no ollama on Shield) + the
# Windows-only shell paragraph + the one ollama subagent line, then banner it.
function Sync-Claude-Md {
  # .NET IO so UTF-8 (em-dashes etc.) round-trips correctly under PS 5.1, which
  # otherwise reads as ANSI and writes a BOM.
  $text  = [IO.File]::ReadAllText((Join-Path $src 'CLAUDE.md'), [Text.Encoding]::UTF8)
  $parts = [regex]::Split($text, '(?m)(?=^## )')
  $kept  = $parts | Where-Object { $_ -notmatch '^## (Local LLM offload|Local pre-filter)' }
  $out   = ($kept -join '').TrimEnd()
  $out   = $out -replace '(?ms)\r?\n\r?\n\*\*Shell selection \(Windows\).*?(?=\r?\n\r?\nAlways batch)', ''
  $out   = $out -replace '(?m)^Step \*down\* to \*\*local ollama\*\*.*\r?\n', ''
  $nl    = "`r`n"
  $banner = "# Shield Claude - synced from DEVIL ~/.claude$nl" +
            "<!-- GENERATED by tools/export-claude-env.ps1. Edit the PC global CLAUDE.md, not this. -->$nl" +
            "<!-- Local-LLM offload + Windows-shell rules stripped: the Shield has no ollama. -->$nl$nl"
  [IO.File]::WriteAllText((Join-Path $dst 'CLAUDE.md'), ($banner + $out), (New-Object Text.UTF8Encoding($false)))
  $hasOffload = ($banner + $out) -match 'ollama'
  Write-Host "synced CLAUDE.md (offload stripped; residual 'ollama' mentions: $hasOffload)"
}

New-Item -ItemType Directory -Path $dst -Force | Out-Null
Sync-Claude-Md
# User-authored, public-safe steering only. Plugin skills (council/find-skills/
# playwright-best-practices) are intentionally NOT synced - plugin-provided, and
# council embeds personal workstation paths.
Sync-Dir 'skills' @('bedazzle', 'caveman', 'parallel-dispatch-gate')
Sync-Dir 'agents' @('classify-cheap.md', 'explore-cheap.md', 'research-cheap.md', 'summarize-cheap.md')
Assert-NoPII
Write-Host ""
Write-Host "claude-env/ regenerated at $dst"
Write-Host "settings.json is the hand-authored Shield variant - exporter leaves it."
